#ifndef __WUKONG_AI_AGENT_H__
#define __WUKONG_AI_AGENT_H__

#include "tuya_cloud_types.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    WUKONG_AI_EVENT_IDLE = -1,
    WUKONG_AI_EVENT_ASR_EMPTY = 0,
    WUKONG_AI_EVENT_ASR_OK,
    WUKONG_AI_EVENT_ASR_ERROR,
    WUKONG_AI_EVENT_TTS_PRE,
    WUKONG_AI_EVENT_TTS_START,
    WUKONG_AI_EVENT_TTS_DATA,
    WUKONG_AI_EVENT_TTS_STOP,
    WUKONG_AI_EVENT_TTS_ABORT,
    WUKONG_AI_EVENT_TTS_ERROR,
    WUKONG_AI_EVENT_VAD_TIMEOUT,
    WUKONG_AI_EVENT_TEXT_STREAM_START,  // 10
    WUKONG_AI_EVENT_TEXT_STREAM_DATA,
    WUKONG_AI_EVENT_TEXT_STREAM_STOP,
    WUKONG_AI_EVENT_TEXT_STREAM_ABORT,
    WUKONG_AI_EVENT_EMOTION,
    WUKONG_AI_EVENT_LLM_EMOTION,
    WUKONG_AI_EVENT_SKILL,
    WUKONG_AI_EVENT_CHAT_BREAK,
    WUKONG_AI_EVENT_SERVER_VAD,
    WUKONG_AI_EVENT_END,
    WUKONG_AI_EVENT_PLAY_CTL_PLAY,  // 20
    WUKONG_AI_EVENT_PLAY_CTL_RESUME,
    WUKONG_AI_EVENT_PLAY_CTL_PAUSE,
    WUKONG_AI_EVENT_PLAY_CTL_REPLAY,
    WUKONG_AI_EVENT_PLAY_CTL_PREV,
    WUKONG_AI_EVENT_PLAY_CTL_NEXT,
    WUKONG_AI_EVENT_PLAY_CTL_SEQUENTIAL,
    WUKONG_AI_EVENT_PLAY_CTL_SEQUENTIAL_LOOP,
    WUKONG_AI_EVENT_PLAY_CTL_SINGLE_LOOP,
    WUKONG_AI_EVENT_PLAY_CTL_END,
    WUKONG_AI_EVENT_PLAY_END,   // 30
    WUKONG_AI_EVENT_PLAY_ALERT, 
    WUKONG_AI_EVENT_EXIT, 
    WUKONG_AI_EVENT_CLOCK_MCP_COUNTDOWN_TIMER,
    WUKONG_AI_EVENT_CLOCK_MCP_STOPWATCH_TIMER,
    WUKONG_AI_EVENT_CLOCK_MCP_POMODORO_TIMER,
    WUKONG_AI_EVENT_CLOCK_MCP_SCHEDULE,    
} WUKONG_AI_EVENT_TYPE_E;

typedef struct {
    WUKONG_AI_EVENT_TYPE_E type;
    VOID *data;
}WUKONG_AI_EVENT_T;

typedef VOID (*WUKONG_EVENT_OUTPUT)(WUKONG_AI_EVENT_T *event);
OPERATE_RET wukong_ai_agent_init(WUKONG_EVENT_OUTPUT cb);
OPERATE_RET wukong_ai_agent_deinit(VOID);
OPERATE_RET wukong_ai_agent_send_text(CHAR_T *content);
OPERATE_RET wukong_ai_agent_send_file(UINT8_T *data, UINT_T len);
OPERATE_RET wukong_ai_agent_send_image(UINT8_T *data, UINT_T len);
OPERATE_RET wukong_ai_agent_send_video(UINT8_T *data, UINT_T len);
OPERATE_RET wukong_ai_agent_cloud_alert(INT_T type);
OPERATE_RET wukong_ai_agent_role_switch(CHAR_T *role);
VOID wukong_ai_event_notify(WUKONG_AI_EVENT_TYPE_E type, VOID *data);

#ifdef __cplusplus
}
#endif

#endif