/*
tuya_app_config.h
Copyright(C),2018-2020, 涂鸦科技 www.tuya.comm
*/

/* AUTO-GENERATED FILE. DO NOT MODIFY !!!
*
* This config file is automatically generated by tuya cross-build system.
* It should not be modified by hand.
*/

#ifndef TUYA_APP_CONFIG_H
#define TUYA_APP_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define TUYA_MODULE_T5 1
// CONFIG_DISABLE_TUYA_OTA_PACK is not set
// CONFIG_ENABLE_AI_MODE_HOLD is not set
// CONFIG_ENABLE_AI_MODE_ONESHOT is not set
// CONFIG_ENABLE_AI_MODE_WAKEUP is not set
#define ENABLE_AI_MODE_FREE 1
#define USING_BOARD_AUDIO_INPUT 1
#define USING_BOARD_AUDIO_OUTPUT 1
#define T5AI_BOARD 1
// CONFIG_T5AI_BOARD_EYES is not set
// CONFIG_T5AI_BOARD_EVB is not set
// CONFIG_T5AI_BOARD_ROBOT is not set
// CONFIG_T5AI_BOARD_DESKTOP is not set
// CONFIG_WUKONG_BOARD_UBUNTU is not set
// CONFIG_ENABLE_TUYA_CAMERA is not set
// CONFIG_ENABLE_AI_MODE_P2P is not set
#define ENABLE_TUYA_UI 1
#define TUYA_CPU_ARCH_SMP 1
#define TUYA_MULTI_TYPES_LCD 1
// CONFIG_TUYA_APP_DRIVERS_TP is not set
#define RGB565_COLOR_SWAP_LVGL 1
#define RGB888_COLOR_SWAP_LVGL 1
#define TUYA_LVGL_VERSION 8
// CONFIG_TUYA_LINGDONG_GUI is not set
// CONFIG_TUYA_IMG_DIRECT_FLUSH is not set
#define TUYA_LVGL_DRAW_WITH_ARM2D 1
// CONFIG_TUYA_FILE_SYSTEM is not set
#define TUYA_LIBJPEG_TURBO 1
#define TUYA_LIB_FREETYPE 1
#define TUYA_AI_TOY_DEMO 1
// CONFIG_ENABLE_CELLULAR_DONGLE is not set
#define TUYA_AI_CHAT_DEFAULT_MODE 3

//
// AI player Decoder Options
//
#define AI_PLAYER_DECODER_OPUS_ENABLE 1
#define AI_PLAYER_DECODER_OPUS_FRAME_SIZE 40
#define AI_PLAYER_DECODER_OPUS_KBPS 16
// end of AI player Decoder Options

#ifdef __cplusplus
}
#endif

#endif
