#include "tuya_app_config.h"

#ifdef TUYA_MULTI_TYPES_LCD
#include "tal_display_service.h"

static const DISPLAY_INIT_SEQ_T  st77916_init_seq[] = {
    // 硬件复位
    {.type = TY_INIT_RST, .reset = {120, 120, 120}},

    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x28}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF2, .len = 1, .v = {0x28}}},

    {.type = TY_INIT_REG, .reg = {.r = 0x73, .len = 1, .v = {0xF0}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x7C, .len = 1, .v = {0xD1}}},

    {.type = TY_INIT_REG, .reg = {.r = 0x83, .len = 1, .v = {0xE0}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x84, .len = 1, .v = {0x61}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xF2, .len = 1, .v = {0x82}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x01}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF1, .len = 1, .v = {0x01}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xB0, .len = 1, .v = {0x56}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB1, .len = 1, .v = {0x4D}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB2, .len = 1, .v = {0x24}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB4, .len = 1, .v = {0x87}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB5, .len = 1, .v = {0x44}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB6, .len = 1, .v = {0x8B}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB7, .len = 1, .v = {0x40}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB8, .len = 1, .v = {0x86}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBA, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBB, .len = 1, .v = {0x08}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBC, .len = 1, .v = {0x08}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBD, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xC0, .len = 1, .v = {0x80}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC1, .len = 1, .v = {0x10}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC2, .len = 1, .v = {0x37}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC3, .len = 1, .v = {0x80}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC4, .len = 1, .v = {0x10}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC5, .len = 1, .v = {0x37}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC6, .len = 1, .v = {0xA9}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC7, .len = 1, .v = {0x41}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC8, .len = 1, .v = {0x01}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC9, .len = 1, .v = {0xA9}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xCA, .len = 1, .v = {0x41}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xCB, .len = 1, .v = {0x01}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xD0, .len = 1, .v = {0x91}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD1, .len = 1, .v = {0x68}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD2, .len = 1, .v = {0x68}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF5, .len = 2, .v = {0x00, 0xA5}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xDD, .len = 1, .v = {0x4F}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xDE, .len = 1, .v = {0x4F}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xF1, .len = 1, .v = {0x10}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE0, .len = 14, .v = {0xF0, 0x0A, 0x10, 0x09, 0x09, 0x36, 0x35, 0x33, 0x4A, 0x29, 0x15, 0x15, 0x2E, 0x34}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE1, .len = 14, .v = {0xF0, 0x0A, 0x0F, 0x08, 0x08, 0x05, 0x34, 0x33, 0x4A, 0x39, 0x15, 0x15, 0x2D, 0x33}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x10}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF3, .len = 1, .v = {0x10}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xE0, .len = 1, .v = {0x07}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE1, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE2, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE3, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE4, .len = 1, .v = {0xE0}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE5, .len = 1, .v = {0x06}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE6, .len = 1, .v = {0x21}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE7, .len = 1, .v = {0x01}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE8, .len = 1, .v = {0x05}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xE9, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xEA, .len = 1, .v = {0xDA}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xEB, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xEC, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xED, .len = 1, .v = {0x0F}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xEE, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xEF, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xF8, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF9, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xFA, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xFB, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xFC, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xFD, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xFE, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xFF, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0x60, .len = 1, .v = {0x40}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x61, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x62, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x63, .len = 1, .v = {0x42}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x64, .len = 1, .v = {0xD9}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x65, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x66, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x67, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x68, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x69, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x6A, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x6B, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0x70, .len = 1, .v = {0x40}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x71, .len = 1, .v = {0x03}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x72, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x73, .len = 1, .v = {0x42}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x74, .len = 1, .v = {0xD8}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x75, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x76, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x77, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x78, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x79, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x7A, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x7B, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0x80, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x81, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x82, .len = 1, .v = {0x06}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x83, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x84, .len = 1, .v = {0xD6}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x85, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x86, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x87, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x88, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x89, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x8A, .len = 1, .v = {0x08}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x8B, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x8C, .len = 1, .v = {0xD8}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x8D, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x8E, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x8F, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0x90, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x91, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x92, .len = 1, .v = {0x0A}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x93, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x94, .len = 1, .v = {0xDA}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x95, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x96, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x97, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x98, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x99, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x9A, .len = 1, .v = {0x0C}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x9B, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x9C, .len = 1, .v = {0xDC}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x9D, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x9E, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x9F, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xA0, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA1, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA2, .len = 1, .v = {0x05}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA3, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA4, .len = 1, .v = {0xD5}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA5, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA6, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA7, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA8, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xA9, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xAA, .len = 1, .v = {0x07}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xAB, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xAC, .len = 1, .v = {0xD7}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xAD, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xAE, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xAF, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xB0, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB1, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB2, .len = 1, .v = {0x09}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB3, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB4, .len = 1, .v = {0xD9}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB5, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB6, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB7, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB8, .len = 1, .v = {0x48}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xB9, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBA, .len = 1, .v = {0x0B}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBB, .len = 1, .v = {0x02}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBC, .len = 1, .v = {0xDB}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBD, .len = 1, .v = {0x04}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBE, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xBF, .len = 1, .v = {0x00}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xC0, .len = 1, .v = {0x10}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC1, .len = 1, .v = {0x47}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC2, .len = 1, .v = {0x56}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC3, .len = 1, .v = {0x65}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC4, .len = 1, .v = {0x74}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC5, .len = 1, .v = {0x88}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC6, .len = 1, .v = {0x99}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC7, .len = 1, .v = {0x01}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC8, .len = 1, .v = {0xBB}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xC9, .len = 1, .v = {0xAA}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xD0, .len = 1, .v = {0x10}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD1, .len = 1, .v = {0x47}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD2, .len = 1, .v = {0x56}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD3, .len = 1, .v = {0x65}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD4, .len = 1, .v = {0x74}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD5, .len = 1, .v = {0x88}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD6, .len = 1, .v = {0x99}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD7, .len = 1, .v = {0x01}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD8, .len = 1, .v = {0xBB}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xD9, .len = 1, .v = {0xAA}}},

    {.type = TY_INIT_REG, .reg = {.r = 0xF3, .len = 1, .v = {0x01}}},
    {.type = TY_INIT_REG, .reg = {.r = 0xF0, .len = 1, .v = {0x00}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x3A, .len = 1, .v = {0x05}}},       //RGB565
    {.type = TY_INIT_REG, .reg = {.r = 0x36, .len = 1, .v = {0xC0}}},
    {.type = TY_INIT_REG, .reg = {.r = 0x35, .len = 1, .v = {0x00}}},
    
    {.type = TY_INIT_REG, .reg = {.r = 0x21, .len = 0}},
    {.type = TY_INIT_REG, .reg = {.r = 0x11, .len = 0}},

    {.type = TY_INIT_DELAY, .delay_time = 120},

    {.type = TY_INIT_REG, .reg = {.r = 0x29, .len = 0}},

    // 结束标记
    {.type = TY_INIT_CONF_END}
};

const ty_display_device_s  lcd_spi_st77916_device = {
    .type = DISPLAY_SPI,
    .name = "spi_st77916",
    .spi = {
        .width = 360,
        .height = 360,
        .pixel_fmt = TY_PIXEL_FMT_RGB565,
        .cfg = {
            .role = TUYA_SPI_ROLE_MASTER,
            .mode = TUYA_SPI_MODE0,
            .type = TUYA_SPI_AUTO_TYPE,
            .databits = TUYA_SPI_DATA_BIT8,
            .bitorder = TUYA_SPI_ORDER_MSB2LSB,
            .freq_hz = 80000000,
            .spi_dma_flags = 1
        },
        .init_seq = st77916_init_seq,
        .display_cfg = NULL
    }
};
#endif
